### ISSUE TITLE
Climb over a wall bug

### ISSUE THREAD

**Issue by rrreeeyyy** [canvas-ncu/socket-io-demo#2]
We have the bug that person can climb over a wall.
A way to reproduce the problem is in the following steps.
1. Waiting for a while in front of the wall two spaces away.
2. Charge the wall.

**Comment by sawa-zen** [comment]
Hmm...I can't reproduce.
I will try find a bug.
Thanx!

**Comment by rrreeeyyy** [comment]
close refs #6
