### ISSUE TITLE
設計見直し

### ISSUE THREAD

**Issue by sawa-zen** [canvas-ncu/socket-io-demo#4]
アバターの歩く動作にどうしても無理があるので一度見直す。

**Comment by sawa-zen** [comment]
## それぞれのコンポーネントがすべき事を整理

### App(アプリケーションのてっぺん)

#### パラメータ
- ステージ
- 自分のアバター
- アバターリスト

#### メソッド
- マップを生成
- 自分の接続を伝える
  - 自分の操作するアバターを生成
- 他人の接続を監視
  - 他人のアバターを生成

# 

### Avatar

#### パラメータ
- 座標
- 向き
- 歩いているかどうか

#### メソッド
- 歩く
- 止まる
- 自分の座標を返す

# 

### Map

#### パラメータ

#### メソッド
- 障害物かどうかの判定

**Comment by rrreeeyyy** [comment]
:+1:

**Comment by sawa-zen** [comment]
## 歩く動作

start
↓
スプライトアニメーション開始
↓
tweenアニメーション開始
↓ 
tweenアニメーション終了
↓
スプライトアニメーション終了
↓
end

**Comment by sawa-zen** [comment]
これではひとマス毎にスプライトアニメーションが終了してしまうのでアウト :-1:

**Comment by sawa-zen** [comment]
walkメソッドは単体でも１マス歩くという機能を持つべき

**Comment by sawa-zen** [comment]
そもそもアバターはAppではなくMapが管理すべきなのでは？

**Comment by sawa-zen** [comment]
- App
  - Map
    - Avatar
    - Avatar

**Comment by sawa-zen** [comment]
歩けと言われたら止まれと言われるまで歩き続けるべきな気がする

**Comment by sawa-zen** [comment]
そもそもAvararは
- 指定された向きの足踏みは始める
- 止まれと言われたら向いている方向で足踏みを止める
  という機能を持っていればよく、

コマを動かすという役割はAppが持てばよい

歩くスプライトはあくまでスプライトの一つでしか無い

**Comment by sawa-zen** [comment]
動く床とかのこととか思い返すとやはり移動に関してはAppもしくはMapが持つということで良さそう

**Comment by rrreeeyyy** [comment]
Good work.
